<?php
/**
 * @file
 * Migration for the Haskala profile.
 */


/**
 * Implements hook_migrate_api().
 */
function haskala_migrate_migrate_api() {
  $migrations = array(
    // Nodes.
    'HaskalaPeopleMigrate',
    'HaskalaBooksMigrate',
    'HaskalaBookTranslationsMigrate',
    'HaskalaEditionMigrate',
    'HaskalaProductionsMigrate',
    'HaskalaMentionsMigrate',

    // Terms.
    'HaskalaCityTermsMigrate',
  );
  
  $api['api'] = 2;
  $api['groups'] = array(
    'haskala' => array(
      'title' => t('Haskala'),
      'default_format' => 'filtered_html',
    ),
  );

  foreach ($migrations as $migration) {
    $api['migrations'][$migration] = array(
      'class_name' => $migration,
      'group_name' => 'haskala',
    );
  }

  return $api;
}
