<?php
/**
 * @file
 * Code for the Haskala Book feature.
 */

include_once 'haskala_book.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function haskala_book_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 *  Prefaces tab - role in book production of preface writer.
 *  Book producers tab - all fields from production bundle.
 *
 *  @param $book_nid
 *   The book node ID.
 *  @param $person_nid
 *   The writer person node ID.
 *
 *  @return production details nodes.
 */
function haskala_book_get_production($book_nid, $person_nid = NULL) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'production')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_book', 'target_id', $book_nid);
  if ($person_nid) {
    $query->fieldCondition('field_producer', 'target_id', $person_nid);
  }
  $result = $query->execute();
  if (empty($result['node'])) {
    return;
  }
  // If filter by person also, we should get single result.
  if ($person_nid) {
    return node_load(reset($result['node'])->nid);
  }
  return node_load_multiple(array_keys($result['node']));
}


/**
 *  Get tab group fields.
 *
 *  @param $wrapper
 *   The wrapper object.
 *  @param $tab
 *   The tab info.
 *  @param $node_view
 *   The node view array for weight field info.
 * @param $book_nid
 *   The book nid.
 *
 *  @return tab fields array.
 */
function haskala_book_get_tab_fields($wrapper, $tab, $node_view, $book_nid) {

  // Sort fields by weight.
  $tab_fields_sorted = array();
  foreach($tab->children as $field_name) {
    if ($wrapper->$field_name->value()){
      $weight = $node_view[$field_name]['#weight'];
      $tab_fields_sorted[$weight] = $field_name;
    }
  }
  ksort($tab_fields_sorted);

  $tab_fields = array();
  foreach($tab_fields_sorted as $field_name) {

    // Check if the field isn't empty.
    if ($wrapper->$field_name->value()) {
      $field = render($node_view[$field_name]);
      $tab_fields[] = $field;

      // Other names for the author.
      if ($field_name == 'field_original_author') {
        $author_names_as_field = haskala_person_get_names($wrapper->$field_name->value()->nid);
      }

      // Role of preface writer.
      if ($field_name == 'field_writer_of_preface') {
        $production_node = haskala_book_get_production($book_nid, $wrapper->$field_name->value()->nid);
        if ($production_node) {
          $field = field_view_field('node', $production_node, 'field_role');
          $tab_fields[] = $field;
        }
      }
    }
  }
  // Add $author_names to translation tab.
  if ($tab->label == 'Translation' && isset($author_names_as_field)){
    // Move the translation general notes if exist to the end.
    $notes_key = key(preg_grep('/field-translation-notes/', $tab_fields));
    $tab_fields[] = $author_names_as_field;
    if ($notes_key) {
      $notes_element = $tab_fields[$notes_key];
      unset($tab_fields[$notes_key]);
      $tab_fields[] = $notes_element;
    }
  }

  return $tab_fields;
}

/**
 * Create array with hebrew letters, not including sofits.
 *
 * @return array
 */
function haskala_book_hebrew_alphabet_without_sofit() {
  return array(
    'א',
    'ב',
    'ג',
    'ד',
    'ה',
    'ו',
    'ז',
    'ח',
    'ט',
    'י',
    'כ',
    'ל',
    'מ',
    'נ',
    'ס',
    'ע',
    'פ',
    'צ',
    'ק',
    'ר',
    'ש',
    'ת',
  );
}
