<?php
/**
 * @file
 * Code for the Haskala Book feature.
 */

include_once 'haskala_book.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function haskala_book_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 *  Prefaces tab - role in book production of preface writer.
 *
 *  @param $book_nid
 *   The book nid.
 *  @param $person_nid
 *   The writer person nid.
 *
 *  @return production details nid.
 */
function haskala_book_get_production($book_nid, $person_nid) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'production')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_producer', 'target_id', $person_nid)
    ->fieldCondition('field_book', 'target_id', $book_nid);
  $result = $query->execute();
  if (empty($result['node'])) {
    return;
  }
  return reset($result['node'])->nid;
}
