<?php
/**
 * @file
 * Code for the Haskala Terms feature.
 */

include_once 'haskala_terms.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function haskala_terms_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_entity_info_alter().
 */
function haskala_terms_entity_info_alter(&$entity_info) {
  $entity_info['taxonomy_term']['view modes']['detailed'] = array(
    'label' => t('Detailed'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function haskala_terms_field_formatter_info() {
  return array(
    'haskala_terms_detailed' => array(
      'label' => t('Detailed'),
      'field types' => array('taxonomy_term_reference'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function haskala_terms_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  if ($display['type'] != 'haskala_terms_detailed') {
    return;
  }

  $element = array();
  foreach ($items as $delta => $item) {
    $element[$delta] = taxonomy_term_view(taxonomy_term_load($item['tid']), 'detailed');
  }

  return $element;
}
